name: dmg-env

dependencies:
  - pip=23.3
  - python=3.10
  - portaudio
  
  - pip:
    - scipy==1.11.3
    - numpy==1.26.0
    - pytest==7.4.0
    - librosa==0.10.1
    - matplotlib==3.7.2
    - pandas==2.1.1
    - pyserial==3.5
    - pyaudio==0.2.14
    - sounddevice==0.4.6
    - customtkinter==5.2.2
    - cffi==1.16.0
    - pyfirmata==1.1.0
    - pytaglib==3.0.0
    - pyyaml==6.0.1